service: serverless-example

plugins:
  - 'serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-plugin-common-excludes

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-2

functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: ANY
          path: /{proxy+}
