service: serverless-example

plugins:
  - 'serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-plugin-common-excludes

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-2

functions:
  main:
    handler: src/main.handler
    timeout: 15
    environment:
      DB_PORT: '3306'
      DB_HOST: 'moviemangae.caj1lc4wgtzk.ap-northeast-2.rds.amazonaws.com'
      DB_USERNAME: 'Woong'
      DB_PASSWORD: 'goddns12!!'
      DB_NAME: 'movie_mangae'
      NODE_SERVER_PORT: '3002'
    events:
      - http:
          method: ANY
          path: /{proxy+}
